export const COLORS = {
  PAGE_BACKGROUND: "#F9F9F9",
  HEADER_BACKGROUND: "#FFFFFF",
  BLACK: "#010101",
  SECONDARY_TEXT_GRAY: "#A1A1A1",
  EPIPEN_COLOR: "#7AC0E2",
  WHITE: "#FFFFFF",
  DOWNLOAD_SECTION_BLUE: "#65A9F2",
  DOWNLOAD_QR_BORDER: "#4B82BC",
  LIGHTER_GRAY: "#E2E2E2",
} as const;
